KeysDictionary("xcu", (1, 3),
               # All cooler keys:
               Key("coolerTemps",
                   Float(invalid="NaN", units="K", name='setpoint'), 
                   Float(invalid="NaN", units="C", name='reject'), 
                   Float(invalid="NaN", units="K", name='tip'), 
                   Float(invalid="NaN", units="W", name='power'), 
                   help="Cryocooler state. Setpoint, Reject, Tip."),

               # All ion gauge keywords:
               Key("pressure", Float(invalid="NaN", units="Torr"),
                   help="Ion gauge pressure."),

               # All ion pump keywords:
               #  cmd.inform('ionPump%d=%d,%g,%g,%g, %g' % (channel,
               Key("ionpump1",
                   Bool(name='enabled'),
                   Float(name='Voltage', invalid="NaN", units="V"),
                   Float(name='Current', invalid="NaN", units="A"),
                   Float(name='Power', invalid="NaN", units="W"),
                   Float(name='Temperature', invalid="NaN", units="K"),
                   Float(name='Pressure', invalid="NaN", units="Torr"),
                   help="Ion pump status."),
               Key("ionpump2",
                   Bool(name='enabled'),
                   Float(name='Voltage', invalid="NaN", units="V"),
                   Float(name='Current', invalid="NaN", units="A"),
                   Float(name='Power', invalid="NaN", units="W"),
                   Float(name='Temperature', invalid="NaN", units="K"),
                   Float(name='Pressure', invalid="NaN", units="Torr"),
                   help="Ion pump status."),
               Key("ionpump3",
                   Bool(name='enabled'),
                   Float(name='Voltage', invalid="NaN", units="V"),
                   Float(name='Current', invalid="NaN", units="A"),
                   Float(name='Power', invalid="NaN", units="W"),
                   Float(name='Temperature', invalid="NaN", units="K"),
                   Float(name='Pressure', invalid="NaN", units="Torr"),
                   help="Ion pump status. Red#1"),
               Key("ionpump4",
                   Bool(name='enabled'),
                   Float(name='Voltage', invalid="NaN", units="V"),
                   Float(name='Current', invalid="NaN", units="A"),
                   Float(name='Power', invalid="NaN", units="W"),
                   Float(name='Temperature', invalid="NaN", units="K"),
                   Float(name='Pressure', invalid="NaN", units="Torr"),
                   help="Ion pump status. Red#2"),
               Key("ionpump5",
                   Bool(name='enabled'),
                   Float(name='Voltage', invalid="NaN", units="V"),
                   Float(name='Current', invalid="NaN", units="A"),
                   Float(name='Power', invalid="NaN", units="W"),
                   Float(name='Temperature', invalid="NaN", units="K"),
                   Float(name='Pressure', invalid="NaN", units="Torr"),
                   help="Ion pump status."),
               Key("ionpump6",
                   Bool(name='enabled'),
                   Float(name='Voltage', invalid="NaN", units="V"),
                   Float(name='Current', invalid="NaN", units="A"),
                   Float(name='Power', invalid="NaN", units="W"),
                   Float(name='Temperature', invalid="NaN", units="K"),
                   Float(name='Pressure', invalid="NaN", units="Torr"),
                   help="Ion pump status."),

               
               Key("temps", Float(invalid="NaN", units="K")*12,
                   help="Temperatures from the IDG board"),
               Key("tempNames", String(invalid="N/C")*12,
                   help="Names of the temperature probes on the IDG board"),
)
